version: '3.8'
services:
    alertmanager:
        image: prom/alertmanager:${ALERTMANAGER_VERSION:-latest}
        command:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--storage.path=/alertmanager'
        volumes:
            - ./alertmanager-alertmanager.yml:/etc/alertmanager/alertmanager.yml
            - alertmanager_data:/alertmanager
        ports:
            - '${ALERTMANAGER_PORT:-9093}:9093'
        networks:
            - devnet

volumes:
    alertmanager_data:

networks:
    devnet:
