version: "3.8"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:${OTEL_COLLECTOR_VERSION:-latest}
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config-otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "${OTEL_GRPC_PORT:-4317}:4317"   # OTLP gRPC receiver
      - "${OTEL_HTTP_PORT:-4318}:4318"   # OTLP HTTP receiver
      - "${OTEL_METRICS_PORT:-8888}:8888"   # Prometheus metrics exposed by collector
      - "${OTEL_EXPORTER_PORT:-8889}:8889"   # Prometheus exporter
      - "${OTEL_HEALTH_PORT:-13133}:13133" # health_check extension
    depends_on:
      - jaeger
      - prometheus
      - loki
    networks:
      - devnet

networks:
  devnet:
