version: "3.8"
services:
  loki:
    image: grafana/loki:${LOKI_VERSION:-latest}
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - devnet

volumes:
  loki_data:

networks:
  devnet:
    external: true
